--
-- File generated with SQLiteStudio v3.3.3 on Wed Dec 1 17:52:46 2021
--
-- Text encoding used: System
--
PRAGMA foreign_keys = on;
BEGIN TRANSACTION;
INSERT INTO holy_grail_item_finding(player_id, holy_grail_item_id, finding_date, finding_location) SELECT 1, holy_grail_item.holy_grail_item_id, '2020-01-01 10:00:00', 'Found before season 4' FROM holy_grail_item WHERE holy_grail_item.item_name = 'Metalgrid';
INSERT INTO holy_grail_item_finding(player_id, holy_grail_item_id, finding_date, finding_location) SELECT 3, holy_grail_item.holy_grail_item_id, '2020-01-01 10:00:00', 'Found before season 4' FROM holy_grail_item WHERE holy_grail_item.item_name = 'Metalgrid';
INSERT INTO holy_grail_item_finding(player_id, holy_grail_item_id, finding_date, finding_location) SELECT 2, holy_grail_item.holy_grail_item_id, '2020-01-01 10:00:00', 'Found before season 4' FROM holy_grail_item WHERE holy_grail_item.item_name = 'Wisp Projector';
INSERT INTO holy_grail_item_finding(player_id, holy_grail_item_id, finding_date, finding_location) SELECT 1, holy_grail_item.holy_grail_item_id, '2020-01-01 10:00:00', 'Found before season 4' FROM holy_grail_item WHERE holy_grail_item.item_name = 'BK Wedding Band';
INSERT INTO holy_grail_item_finding(player_id, holy_grail_item_id, finding_date, finding_location) SELECT 2, holy_grail_item.holy_grail_item_id, '2020-01-01 10:00:00', 'Found before season 4' FROM holy_grail_item WHERE holy_grail_item.item_name = 'BK Wedding Band';
INSERT INTO holy_grail_item_finding(player_id, holy_grail_item_id, finding_date, finding_location) SELECT 3, holy_grail_item.holy_grail_item_id, '2020-01-01 10:00:00', 'Found before season 4' FROM holy_grail_item WHERE holy_grail_item.item_name = 'BK Wedding Band';
INSERT INTO holy_grail_item_finding(player_id, holy_grail_item_id, finding_date, finding_location) SELECT 1, holy_grail_item.holy_grail_item_id, '2020-01-01 10:00:00', 'Found before season 4' FROM holy_grail_item WHERE holy_grail_item.item_name = 'Stone of Jordan';
INSERT INTO holy_grail_item_finding(player_id, holy_grail_item_id, finding_date, finding_location) SELECT 2, holy_grail_item.holy_grail_item_id, '2020-01-01 10:00:00', 'Found before season 4' FROM holy_grail_item WHERE holy_grail_item.item_name = 'Stone of Jordan';
INSERT INTO holy_grail_item_finding(player_id, holy_grail_item_id, finding_date, finding_location) SELECT 3, holy_grail_item.holy_grail_item_id, '2020-01-01 10:00:00', 'Found before season 4' FROM holy_grail_item WHERE holy_grail_item.item_name = 'Stone of Jordan';
INSERT INTO holy_grail_item_finding(player_id, holy_grail_item_id, finding_date, finding_location) SELECT 2, holy_grail_item.holy_grail_item_id, '2020-01-01 10:00:00', 'Found before season 4' FROM holy_grail_item WHERE holy_grail_item.item_name = 'Templars Might';
INSERT INTO holy_grail_item_finding(player_id, holy_grail_item_id, finding_date, finding_location) SELECT 2, holy_grail_item.holy_grail_item_id, '2020-01-01 10:00:00', 'Found before season 4' FROM holy_grail_item WHERE holy_grail_item.item_name = 'Steelrend';
INSERT INTO holy_grail_item_finding(player_id, holy_grail_item_id, finding_date, finding_location) SELECT 1, holy_grail_item.holy_grail_item_id, '2020-01-01 10:00:00', 'Found before season 4' FROM holy_grail_item WHERE holy_grail_item.item_name = 'Steelrend';
INSERT INTO holy_grail_item_finding(player_id, holy_grail_item_id, finding_date, finding_location) SELECT 2, holy_grail_item.holy_grail_item_id, '2020-01-01 10:00:00', 'Found before season 4' FROM holy_grail_item WHERE holy_grail_item.item_name = 'Veil of Steel';
INSERT INTO holy_grail_item_finding(player_id, holy_grail_item_id, finding_date, finding_location) SELECT 1, holy_grail_item.holy_grail_item_id, '2020-01-01 10:00:00', 'Found before season 4' FROM holy_grail_item WHERE holy_grail_item.item_name = 'Death Cleaver';
INSERT INTO holy_grail_item_finding(player_id, holy_grail_item_id, finding_date, finding_location) SELECT 1, holy_grail_item.holy_grail_item_id, '2020-01-01 10:00:00', 'Found before season 4' FROM holy_grail_item WHERE holy_grail_item.item_name = 'Nightwings Veil';
INSERT INTO holy_grail_item_finding(player_id, holy_grail_item_id, finding_date, finding_location) SELECT 1, holy_grail_item.holy_grail_item_id, '2020-01-01 10:00:00', 'Found before season 4' FROM holy_grail_item WHERE holy_grail_item.item_name = 'Crown of Ages';
INSERT INTO holy_grail_item_finding(player_id, holy_grail_item_id, finding_date, finding_location) SELECT 2, holy_grail_item.holy_grail_item_id, '2020-01-01 10:00:00', 'Found before season 4' FROM holy_grail_item WHERE holy_grail_item.item_name = 'Crown of Ages';
INSERT INTO holy_grail_item_finding(player_id, holy_grail_item_id, finding_date, finding_location) SELECT 1, holy_grail_item.holy_grail_item_id, '2020-01-01 10:00:00', 'Found before season 4' FROM holy_grail_item WHERE holy_grail_item.item_name = 'Griffons Eye';
INSERT INTO holy_grail_item_finding(player_id, holy_grail_item_id, finding_date, finding_location) SELECT 2, holy_grail_item.holy_grail_item_id, '2020-01-01 10:00:00', 'Found before season 4' FROM holy_grail_item WHERE holy_grail_item.item_name = 'Griffons Eye';
INSERT INTO holy_grail_item_finding(player_id, holy_grail_item_id, finding_date, finding_location) SELECT 1, holy_grail_item.holy_grail_item_id, '2020-01-01 10:00:00', 'Found before season 4' FROM holy_grail_item WHERE holy_grail_item.item_name = 'Ravenlore';
INSERT INTO holy_grail_item_finding(player_id, holy_grail_item_id, finding_date, finding_location) SELECT 1, holy_grail_item.holy_grail_item_id, '2020-01-01 10:00:00', 'Found before season 4' FROM holy_grail_item WHERE holy_grail_item.item_name = 'Stormspire';
INSERT INTO holy_grail_item_finding(player_id, holy_grail_item_id, finding_date, finding_location) SELECT 1, holy_grail_item.holy_grail_item_id, '2020-01-01 10:00:00', 'Found before season 4' FROM holy_grail_item WHERE holy_grail_item.item_name = 'Astreons Iron Ward';
INSERT INTO holy_grail_item_finding(player_id, holy_grail_item_id, finding_date, finding_location) SELECT 1, holy_grail_item.holy_grail_item_id, '2020-01-01 10:00:00', 'Found before season 4' FROM holy_grail_item WHERE holy_grail_item.item_name = 'Ghostflame';
INSERT INTO holy_grail_item_finding(player_id, holy_grail_item_id, finding_date, finding_location) SELECT 1, holy_grail_item.holy_grail_item_id, '2020-01-01 10:00:00', 'Found before season 4' FROM holy_grail_item WHERE holy_grail_item.item_name = 'Executioners Justice';
INSERT INTO holy_grail_item_finding(player_id, holy_grail_item_id, finding_date, finding_location) SELECT 1, holy_grail_item.holy_grail_item_id, '2020-01-01 10:00:00', 'Found before season 4' FROM holy_grail_item WHERE holy_grail_item.item_name = 'Boneflame';
INSERT INTO holy_grail_item_finding(player_id, holy_grail_item_id, finding_date, finding_location) SELECT 1, holy_grail_item.holy_grail_item_id, '2020-01-01 10:00:00', 'Found before season 4' FROM holy_grail_item WHERE holy_grail_item.item_name = 'The Cranium Basher';
INSERT INTO holy_grail_item_finding(player_id, holy_grail_item_id, finding_date, finding_location) SELECT 2, holy_grail_item.holy_grail_item_id, '2020-01-01 10:00:00', 'Found before season 4' FROM holy_grail_item WHERE holy_grail_item.item_name = 'The Cranium Basher';
INSERT INTO holy_grail_item_finding(player_id, holy_grail_item_id, finding_date, finding_location) SELECT 3, holy_grail_item.holy_grail_item_id, '2020-01-01 10:00:00', 'Found before season 4' FROM holy_grail_item WHERE holy_grail_item.item_name = 'The Cranium Basher';
INSERT INTO holy_grail_item_finding(player_id, holy_grail_item_id, finding_date, finding_location) SELECT 2, holy_grail_item.holy_grail_item_id, '2020-01-01 10:00:00', 'Found before season 4' FROM holy_grail_item WHERE holy_grail_item.item_name = 'Stormlash';
INSERT INTO holy_grail_item_finding(player_id, holy_grail_item_id, finding_date, finding_location) SELECT 1, holy_grail_item.holy_grail_item_id, '2020-01-01 10:00:00', 'Found before season 4' FROM holy_grail_item WHERE holy_grail_item.item_name = 'Stormlash';
INSERT INTO holy_grail_item_finding(player_id, holy_grail_item_id, finding_date, finding_location) SELECT 2, holy_grail_item.holy_grail_item_id, '2020-01-01 10:00:00', 'Found before season 4' FROM holy_grail_item WHERE holy_grail_item.item_name = 'The Grandfather';
INSERT INTO holy_grail_item_finding(player_id, holy_grail_item_id, finding_date, finding_location) SELECT 1, holy_grail_item.holy_grail_item_id, '2020-01-01 10:00:00', 'Found before season 4' FROM holy_grail_item WHERE holy_grail_item.item_name = 'Deaths Fathom';
INSERT INTO holy_grail_item_finding(player_id, holy_grail_item_id, finding_date, finding_location) SELECT 1, holy_grail_item.holy_grail_item_id, '2020-01-01 10:00:00', 'Found before season 4' FROM holy_grail_item WHERE holy_grail_item.item_name = 'Deaths Web';
INSERT INTO holy_grail_item_finding(player_id, holy_grail_item_id, finding_date, finding_location) SELECT 2, holy_grail_item.holy_grail_item_id, '2020-01-01 10:00:00', 'Found before season 4' FROM holy_grail_item WHERE holy_grail_item.item_name = 'Deaths Web';
INSERT INTO holy_grail_item_finding(player_id, holy_grail_item_id, finding_date, finding_location) SELECT 2, holy_grail_item.holy_grail_item_id, '2020-01-01 10:00:00', 'Found before season 4' FROM holy_grail_item WHERE holy_grail_item.item_name = 'Mang Songs Lesson';
INSERT INTO holy_grail_item_finding(player_id, holy_grail_item_id, finding_date, finding_location) SELECT 1, holy_grail_item.holy_grail_item_id, '2020-01-01 10:00:00', 'Found before season 4' FROM holy_grail_item WHERE holy_grail_item.item_name = 'Gargoyles Bite';
INSERT INTO holy_grail_item_finding(player_id, holy_grail_item_id, finding_date, finding_location) SELECT 1, holy_grail_item.holy_grail_item_id, '2020-01-01 10:00:00', 'Found before season 4' FROM holy_grail_item WHERE holy_grail_item.item_name = 'Steel Pillar';


COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
